# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.extract_pdf_success_pages_inner_text_blocks_inner import ExtractPdfSuccessPagesInnerTextBlocksInner  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestExtractPdfSuccessPagesInnerTextBlocksInner(unittest.TestCase):
    """ExtractPdfSuccessPagesInnerTextBlocksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ExtractPdfSuccessPagesInnerTextBlocksInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractPdfSuccessPagesInnerTextBlocksInner`
        """
        model = gradientai.openapi.client.models.extract_pdf_success_pages_inner_text_blocks_inner.ExtractPdfSuccessPagesInnerTextBlocksInner()  # noqa: E501
        if include_optional :
            return ExtractPdfSuccessPagesInnerTextBlocksInner(
                kind = 'footer', 
                texts = [
                    ''
                    ]
            )
        else :
            return ExtractPdfSuccessPagesInnerTextBlocksInner(
                kind = 'footer',
                texts = [
                    ''
                    ],
        )
        """

    def testExtractPdfSuccessPagesInnerTextBlocksInner(self):
        """Test ExtractPdfSuccessPagesInnerTextBlocksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
