# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.get_audio_transcription_success_one_of1 import GetAudioTranscriptionSuccessOneOf1  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestGetAudioTranscriptionSuccessOneOf1(unittest.TestCase):
    """GetAudioTranscriptionSuccessOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAudioTranscriptionSuccessOneOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAudioTranscriptionSuccessOneOf1`
        """
        model = gradientai.openapi.client.models.get_audio_transcription_success_one_of1.GetAudioTranscriptionSuccessOneOf1()  # noqa: E501
        if include_optional :
            return GetAudioTranscriptionSuccessOneOf1(
                result = gradientai.openapi.client.models.get_audio_transcription_success_one_of_1_result.GetAudioTranscriptionSuccess_oneOf_1_result(
                    text = '', ), 
                status = 'succeeded'
            )
        else :
            return GetAudioTranscriptionSuccessOneOf1(
                result = gradientai.openapi.client.models.get_audio_transcription_success_one_of_1_result.GetAudioTranscriptionSuccess_oneOf_1_result(
                    text = '', ),
                status = 'succeeded',
        )
        """

    def testGetAudioTranscriptionSuccessOneOf1(self):
        """Test GetAudioTranscriptionSuccessOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
