# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.personalize_document_success import PersonalizeDocumentSuccess  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestPersonalizeDocumentSuccess(unittest.TestCase):
    """PersonalizeDocumentSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PersonalizeDocumentSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonalizeDocumentSuccess`
        """
        model = gradientai.openapi.client.models.personalize_document_success.PersonalizeDocumentSuccess()  # noqa: E501
        if include_optional :
            return PersonalizeDocumentSuccess(
                personalized_document = '0'
            )
        else :
            return PersonalizeDocumentSuccess(
                personalized_document = '0',
        )
        """

    def testPersonalizeDocumentSuccess(self):
        """Test PersonalizeDocumentSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
