# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.complete_model_body_params import CompleteModelBodyParams  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestCompleteModelBodyParams(unittest.TestCase):
    """CompleteModelBodyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CompleteModelBodyParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteModelBodyParams`
        """
        model = gradientai.openapi.client.models.complete_model_body_params.CompleteModelBodyParams()  # noqa: E501
        if include_optional :
            return CompleteModelBodyParams(
                auto_template = True, 
                guidance = gradientai.openapi.client.models.complete_model_body_params_guidance.CompleteModelBodyParams_guidance(
                    type = 'choice', 
                    value = [
                        '0'
                        ], ), 
                max_generated_token_count = 0, 
                query = '0', 
                rag = gradientai.openapi.client.models.complete_model_body_params_rag.CompleteModelBodyParams_rag(
                    collection_id = '0', ), 
                temperature = 1.337, 
                top_k = 56, 
                top_p = 1.337
            )
        else :
            return CompleteModelBodyParams(
                query = '0',
        )
        """

    def testCompleteModelBodyParams(self):
        """Test CompleteModelBodyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
