# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import gradientai.openapi.client
from gradientai.openapi.client.api.models_api import ModelsApi  # noqa: E501
from gradientai.openapi.client.rest import ApiException


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self):
        self.api = gradientai.openapi.client.api.models_api.ModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_complete_model(self):
        """Test case for complete_model

        Complete model  # noqa: E501
        """
        pass

    def test_create_model(self):
        """Test case for create_model

        Create model  # noqa: E501
        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        Delete model  # noqa: E501
        """
        pass

    def test_fine_tune_model(self):
        """Test case for fine_tune_model

        Fine-tune model  # noqa: E501
        """
        pass

    def test_get_model(self):
        """Test case for get_model

        Describe model  # noqa: E501
        """
        pass

    def test_list_models(self):
        """Test case for list_models

        List available models  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
