# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import gradientai.openapi.client
from gradientai.openapi.client.api.files_api import FilesApi  # noqa: E501
from gradientai.openapi.client.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = gradientai.openapi.client.api.files_api.FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_file(self):
        """Test case for upload_file

        File upload  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
