# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.generate_answer_success import GenerateAnswerSuccess  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestGenerateAnswerSuccess(unittest.TestCase):
    """GenerateAnswerSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GenerateAnswerSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateAnswerSuccess`
        """
        model = gradientai.openapi.client.models.generate_answer_success.GenerateAnswerSuccess()  # noqa: E501
        if include_optional :
            return GenerateAnswerSuccess(
                answer = '0', 
                rag_context = gradientai.openapi.client.models.generate_answer_success_rag_context.GenerateAnswerSuccess_ragContext(
                    documents = [
                        gradientai.openapi.client.models.generate_answer_success_rag_context_documents_inner.GenerateAnswerSuccess_ragContext_documents_inner(
                            content = '0', 
                            file_name = '0', )
                        ], )
            )
        else :
            return GenerateAnswerSuccess(
                answer = '0',
        )
        """

    def testGenerateAnswerSuccess(self):
        """Test GenerateAnswerSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
