# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.fine_tune_model_error import FineTuneModelError  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestFineTuneModelError(unittest.TestCase):
    """FineTuneModelError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FineTuneModelError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuneModelError`
        """
        model = gradientai.openapi.client.models.fine_tune_model_error.FineTuneModelError()  # noqa: E501
        if include_optional :
            return FineTuneModelError(
                message = '0', 
                payload = gradientai.openapi.client.models.complete_model_error_one_of_1_payload.CompleteModelError_oneOf_1_payload(
                    formatted_validation_error = null, 
                    validation_error = null, ), 
                type = 'bodyParsingError'
            )
        else :
            return FineTuneModelError(
                message = '0',
                payload = gradientai.openapi.client.models.complete_model_error_one_of_1_payload.CompleteModelError_oneOf_1_payload(
                    formatted_validation_error = null, 
                    validation_error = null, ),
                type = 'bodyParsingError',
        )
        """

    def testFineTuneModelError(self):
        """Test FineTuneModelError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
