# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.summarize_document_body_params import SummarizeDocumentBodyParams  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestSummarizeDocumentBodyParams(unittest.TestCase):
    """SummarizeDocumentBodyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SummarizeDocumentBodyParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SummarizeDocumentBodyParams`
        """
        model = gradientai.openapi.client.models.summarize_document_body_params.SummarizeDocumentBodyParams()  # noqa: E501
        if include_optional :
            return SummarizeDocumentBodyParams(
                document = '0', 
                examples = [
                    gradientai.openapi.client.models.summarize_document_body_params_examples_inner.SummarizeDocumentBodyParams_examples_inner(
                        document = '0', 
                        summary = '0', )
                    ], 
                length = 'short'
            )
        else :
            return SummarizeDocumentBodyParams(
                document = '0',
        )
        """

    def testSummarizeDocumentBodyParams(self):
        """Test SummarizeDocumentBodyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
