# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import gradientai.openapi.client
from gradientai.openapi.client.api.embeddings_api import EmbeddingsApi  # noqa: E501
from gradientai.openapi.client.rest import ApiException


class TestEmbeddingsApi(unittest.TestCase):
    """EmbeddingsApi unit test stubs"""

    def setUp(self):
        self.api = gradientai.openapi.client.api.embeddings_api.EmbeddingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_embedding(self):
        """Test case for generate_embedding

        Generate embeddings  # noqa: E501
        """
        pass

    def test_list_embeddings(self):
        """Test case for list_embeddings

        List available embeddings models  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
