# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import gradientai.openapi.client
from gradientai.openapi.client.api.blocks_api import BlocksApi  # noqa: E501
from gradientai.openapi.client.rest import ApiException


class TestBlocksApi(unittest.TestCase):
    """BlocksApi unit test stubs"""

    def setUp(self):
        self.api = gradientai.openapi.client.api.blocks_api.BlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyze_sentiment(self):
        """Test case for analyze_sentiment

        Sentiment analysis  # noqa: E501
        """
        pass

    def test_extract_entity(self):
        """Test case for extract_entity

        Entity extraction  # noqa: E501
        """
        pass

    def test_extract_pdf(self):
        """Test case for extract_pdf

        PDF extraction  # noqa: E501
        """
        pass

    def test_generate_answer(self):
        """Test case for generate_answer

        Document question & answer  # noqa: E501
        """
        pass

    def test_personalize_document(self):
        """Test case for personalize_document

        Document personalization  # noqa: E501
        """
        pass

    def test_summarize_document(self):
        """Test case for summarize_document

        Document summary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
