# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.complete_model_error_one_of4 import CompleteModelErrorOneOf4  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestCompleteModelErrorOneOf4(unittest.TestCase):
    """CompleteModelErrorOneOf4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CompleteModelErrorOneOf4
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteModelErrorOneOf4`
        """
        model = gradientai.openapi.client.models.complete_model_error_one_of4.CompleteModelErrorOneOf4()  # noqa: E501
        if include_optional :
            return CompleteModelErrorOneOf4(
                message = '0', 
                type = 'modelDoesNotSupportGuidance'
            )
        else :
            return CompleteModelErrorOneOf4(
                message = '0',
                type = 'modelDoesNotSupportGuidance',
        )
        """

    def testCompleteModelErrorOneOf4(self):
        """Test CompleteModelErrorOneOf4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
