# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.list_models_success_models_inner import ListModelsSuccessModelsInner  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestListModelsSuccessModelsInner(unittest.TestCase):
    """ListModelsSuccessModelsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListModelsSuccessModelsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListModelsSuccessModelsInner`
        """
        model = gradientai.openapi.client.models.list_models_success_models_inner.ListModelsSuccessModelsInner()  # noqa: E501
        if include_optional :
            return ListModelsSuccessModelsInner(
                capabilities = [
                    'complete'
                    ], 
                id = '012345678910111213141516171819202122232425262728293031323334353637383940414243444546474849', 
                name = '0', 
                slug = '0', 
                type = 'baseModel', 
                base_model_id = '0', 
                latest_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return ListModelsSuccessModelsInner(
                capabilities = [
                    'complete'
                    ],
                id = '012345678910111213141516171819202122232425262728293031323334353637383940414243444546474849',
                name = '0',
                slug = '0',
                type = 'baseModel',
                base_model_id = '0',
                latest_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testListModelsSuccessModelsInner(self):
        """Test ListModelsSuccessModelsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
