# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.base_model import BaseModel  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestBaseModel(unittest.TestCase):
    """BaseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BaseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseModel`
        """
        model = gradientai.openapi.client.models.base_model.BaseModel()  # noqa: E501
        if include_optional :
            return BaseModel(
                capabilities = [
                    'complete'
                    ], 
                id = '012345678910111213141516171819202122232425262728293031323334353637383940414243444546474849', 
                name = '0', 
                slug = '0', 
                type = 'baseModel'
            )
        else :
            return BaseModel(
                capabilities = [
                    'complete'
                    ],
                id = '012345678910111213141516171819202122232425262728293031323334353637383940414243444546474849',
                name = '0',
                slug = '0',
                type = 'baseModel',
        )
        """

    def testBaseModel(self):
        """Test BaseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
