# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import gradientai.openapi.client
from gradientai.openapi.client.models.fine_tune_model_body_params_samples_inner_inputs_any_of_inner import FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner  # noqa: E501
from gradientai.openapi.client.rest import ApiException

class TestFineTuneModelBodyParamsSamplesInnerInputsAnyOfInner(unittest.TestCase):
    """FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner`
        """
        model = gradientai.openapi.client.models.fine_tune_model_body_params_samples_inner_inputs_any_of_inner.FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner()  # noqa: E501
        if include_optional :
            return FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner(
                parse_special_tokens = True, 
                trainable = True, 
                value = '0'
            )
        else :
            return FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner(
                value = '0',
        )
        """

    def testFineTuneModelBodyParamsSamplesInnerInputsAnyOfInner(self):
        """Test FineTuneModelBodyParamsSamplesInnerInputsAnyOfInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
