# coding: utf-8

"""
    Gradient AI API

    Interface for interacting with Gradient AI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@gradient.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict
from pydantic import BaseModel, Field
from gradientai.openapi.client.models.extract_entity_success_entity_value import ExtractEntitySuccessEntityValue

class ExtractEntitySuccess(BaseModel):
    """
    ExtractEntitySuccess
    """
    entity: Dict[str, ExtractEntitySuccessEntityValue] = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["entity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExtractEntitySuccess:
        """Create an instance of ExtractEntitySuccess from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each value in entity (dict)
        _field_dict = {}
        if self.entity:
            for _key in self.entity:
                if self.entity[_key]:
                    _field_dict[_key] = self.entity[_key].to_dict()
            _dict['entity'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExtractEntitySuccess:
        """Create an instance of ExtractEntitySuccess from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExtractEntitySuccess.parse_obj(obj)

        _obj = ExtractEntitySuccess.parse_obj({
            "entity": dict(
                (_k, ExtractEntitySuccessEntityValue.from_dict(_v))
                for _k, _v in obj.get("entity").items()
            )
            if obj.get("entity") is not None
            else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

